#!/usr/bin/env python3
"""
Generate AI summaries for OTel SIG meeting transcripts.

Walks docs/content/, calls OpenAI gpt-4o-mini for each transcript
that doesn't already have a summary, and writes the result to
docs/content/{slug}/{date}/summary.md.
"""

from __future__ import annotations

import argparse
import os
import time
from datetime import date, timedelta
from pathlib import Path
from typing import TYPE_CHECKING

from scraper.otel_setup import StatusCode, _NoOpTracer, configure_tracer
from scraper.transcript_io import (
    MIN_TRANSCRIPT_LINES,
    count_transcript_lines,
    parse_header,
)
from scraper.transcript_io import (
    read_transcript_body as _read_transcript_body,
)

if TYPE_CHECKING:
    from openai import OpenAI

ROOT = Path(__file__).parent
DOCS_TRANSCRIPTS_DIR = ROOT / "docs" / "content"

MAX_TRANSCRIPT_CHARS = 80_000
_API_RATE_LIMIT_S = 1


def read_transcript_body(path: Path) -> str:
    """Read a transcript and return only the Zoom Recording Transcript section.

    Delegates to scraper.transcript_io.read_transcript_body, then truncates
    to MAX_TRANSCRIPT_CHARS to stay within OpenAI token limits.
    """
    body = _read_transcript_body(path)
    if len(body) > MAX_TRANSCRIPT_CHARS:
        body = body[:MAX_TRANSCRIPT_CHARS]
    return body


def generate_summary(
    client: OpenAI,
    sig_name: str,
    date: str,
    duration: str,
    transcript_body: str,
) -> str:
    """Call OpenAI to generate a summary of the transcript."""
    prompt = (
        f"Summarize this OpenTelemetry {sig_name} meeting transcript from {date} "
        f"({duration} minutes). Format your response EXACTLY as Markdown with these sections:\n\n"
        "## Key Topics\n- ...\n\n"
        "## Action Items\n- ...\n\n"
        "## Participants\nName1, Name2, ...\n\n"
        "Be concise. List 3-5 key topics and any action items mentioned.\n\n"
        "Note: the transcript is auto-generated by Zoom's speech-to-text and "
        "frequently renders 'OpenTelemetry' or 'OTel' as 'Hotel', 'O'Tell', "
        "or similar artifacts (e.g. 'Hotel Arrow', 'Hotel Unplugged', "
        "'Hotel Blueprints', 'O'Tell Me'). When the surrounding context "
        "makes clear that the artifact refers to OpenTelemetry, use 'OTel' "
        "or 'OpenTelemetry' in your output instead. If the speaker genuinely "
        "means lodging, a venue, or another non-OTel sense, leave the term "
        "as-is."
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You summarize meeting transcripts concisely."},
            {"role": "user", "content": f"{prompt}\n\n---\n\n{transcript_body}"},
        ],
        temperature=0.3,
        max_tokens=1500,
    )
    return response.choices[0].message.content


def process_transcripts(
    client: OpenAI,
    transcripts_dir: Path = DOCS_TRANSCRIPTS_DIR,
    since: date | None = None,
    until: date | None = None,
    tracer: object = None,
) -> tuple[int, int]:
    """Process transcripts in the given date range and generate missing summaries.

    When neither ``since`` nor ``until`` is provided, defaults to the last 2 weeks.
    Returns (generated_count, skipped_count).
    """
    if tracer is None:
        tracer = _NoOpTracer()

    generated = 0
    skipped = 0

    if since is None and until is None:
        since = date.today() - timedelta(weeks=2)

    for txt_path in sorted(transcripts_dir.glob("*/*/transcript.md")):
        slug = txt_path.parent.parent.name
        date_str = txt_path.parent.name

        try:
            meeting_date = date.fromisoformat(date_str)
        except ValueError:
            continue
        if since is not None and meeting_date < since:
            skipped += 1
            continue
        if until is not None and meeting_date > until:
            skipped += 1
            continue

        summary_path = txt_path.parent / "summary.md"
        if summary_path.exists():
            skipped += 1
            continue

        header = parse_header(txt_path)
        if header is None:
            print(f"  WARNING: skipping {txt_path} (unparseable header)")
            continue

        body = read_transcript_body(txt_path)
        if not body.strip():
            print(f"  WARNING: skipping {txt_path} (empty transcript body)")
            continue

        line_count = count_transcript_lines(body)
        if line_count < MIN_TRANSCRIPT_LINES:
            print(f"  WARNING: skipping {txt_path} (trivial transcript: {line_count} lines)")
            skipped += 1
            continue

        print(f"  Generating summary for {slug}/{date_str}...")
        with tracer.start_as_current_span("generate summary") as span:
            span.set_attribute("sig.slug", slug)
            span.set_attribute("meeting.date", date_str)
            span.set_attribute("transcript.lines", line_count)
            try:
                summary_text = generate_summary(
                    client,
                    header["sig_name"],
                    header["date"],
                    str(header["duration_minutes"]),
                    body,
                )
            except Exception as exc:  # noqa: BLE001
                span.record_exception(exc)
                span.set_status(StatusCode.ERROR, str(exc))
                raise

        summary_path.write_text(summary_text + "\n", encoding="utf-8")
        generated += 1

        time.sleep(_API_RATE_LIMIT_S)

    return generated, skipped


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate AI summaries for OTel SIG transcripts.")
    parser.add_argument(
        "--since", metavar="YYYY-MM-DD", help="Only process meetings on or after this date."
    )
    parser.add_argument(
        "--until", metavar="YYYY-MM-DD", help="Only process meetings on or before this date."
    )
    args = parser.parse_args()

    since = date.fromisoformat(args.since) if args.since else None
    until = date.fromisoformat(args.until) if args.until else None

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("ERROR: OPENAI_API_KEY environment variable is not set")
        raise SystemExit(1)

    tracer = configure_tracer("otel-recordings-summarize")

    from openai import (
        OpenAI,  # noqa: PLC0415 — deferred; must come after configure_tracer so OpenAIInstrumentor patches first
    )

    client = OpenAI(api_key=api_key)

    with tracer.start_as_current_span("generate summaries") as span:
        if args.since:
            span.set_attribute("filter.since_date", args.since)
        if args.until:
            span.set_attribute("filter.until_date", args.until)

        generated, skipped = process_transcripts(client, since=since, until=until, tracer=tracer)

        span.set_attribute("summaries.generated", generated)
        span.set_attribute("summaries.skipped", skipped)

    print(f"Generated {generated} summaries, skipped {skipped} existing")


if __name__ == "__main__":  # pragma: no cover
    main()
